# 端口
server:
  port: 8061

spring:
  main:
    # Bean同名注册出现的bug，true则是覆盖同名注册的Bean
    allow-bean-definition-overriding: true
  application:
    name: weiran-uaa
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址 ,暂且只配置服务发现管理，配置管理暂且没有弄
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 0.1 #设置Sleuth的抽样收集概率
  boot:
    admin:
      client:
        url: http://localhost:9301 #配置admin-server地址
        instance:
          name: weiran
          metadata:
            username: sun
            password: 123 #配置不对,暂时只能在satoken过滤器那放开actuator路径
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/auth?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
  thymeleaf:
    cache: false
  # redis Sa-token的框架集成，只需要引入maven依赖就可以了
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 123456
    # 连接超时时间（毫秒）
    timeout: 5000
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

# sa-token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 60
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: 60
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

# 这个与依赖mybatis-plus-boot-starter对应，mybatis-plus依赖包则是mybatis.mapper-locations
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:logback.xml

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

#logging:
#  file:
#    name: admin-client.log #添加开启admin的日志监控



